export const enum EventType {
  ProgramStart = 'program start',
  ProgramEnd = 'program end',
  LoopStart = 'loop start',
  LoopEnd = 'loop end',
  Break = 'break',
  Ifz = 'ifz',
  Ifp = 'ifp',
  Ifn = 'ifn ',
  IfEnd = 'if end',
  Else = 'else',
  Assignment = 'assignment',
  AssignmentEnd = 'assignment end',
  Number = 'number',
  Operator = 'operator',
  LeftParen = 'left paren',
  RightParen = 'right paren',
  Symbol = 'symbol',
  BlockEnd = 'block end',
  Print = 'print',
  PrintEnd = 'print end',
  Read = 'read',
  ReadEnd = 'read end',
}
